force-app/main/default/objects/Contact/fields/Address_Validated__c.field-meta.xml
<CustomField>
    <fullName>Address_Validated__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Identifies if the address is validated by means of external service</description>
    <label>Address Validated?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/FND_Address_Validation_Settings__c/FND_Address_Validation_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>FND Address Validation Settings</label>
</CustomObject>

force-app/main/default/objects/FND_Address_Validation_Settings__c/fields/Confidence_Threshold__c.field-meta.xml
<CustomField>
    <fullName>Confidence_Threshold__c</fullName>
    <description>Confidence above this threshold will be a validated address</description>
    <label>Confidence Threshold</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/FND_AddresValidatorCtrl.cls
// Controller class for the fndAddressValidator LWC
public with sharing class FND_AddresValidatorCtrl {
    private static FND_Address_Validation_Settings__c addressValidationSettings = FND_Address_Validation_Settings__c.getInstance('Default');

    // Validate the address by using the service class
    @AuraEnabled
    public static Boolean validateAddressWithAPI(Id contactId, FND_AddressRequestDTO addressRequest) {
        // Perform the callout using the service class and save the response in the address response DTO
        FND_AddressResponseDTO addressResponse = FND_AddressAPIService.validateAddress(addressRequest);

        // Log the confidence variable, we use this to validate the address
        Decimal confidence = Decimal.valueOf(addressResponse.features[0].properties.rank.confidence);

        // We can set our threshold to identify what is a validated address or not.
        Boolean addressValidated = confidence >= addressValidationSettings.Confidence_Threshold__c ? true : false;

        // Update the contact using the contactId
        Contact c = new Contact(
            Id = contactId,
            Address_Validated__c = addressValidated
        );

        update c;

        // Return the result of the validation to the LWC
        return addressValidated;
    }
}